# Copyright 2025, Canonical Ltd.
# See LICENSE file for licensing details

[tox]
envlist = lint, unit, integration, mypy, functional
skipsdist = False
sitepackages = False
skip_missing_interpreters = True

[vars]
src_path = {toxinidir}/
tst_path = {toxinidir}/tests/

[testenv]
setenv = VIRTUAL_ENV={envdir}
         PYTHONHASHSEED=0
deps = 
    -e {toxinidir}
    pytest
    pytest-mock
    pytest-cov
    coverage[toml]

[testenv:fmt]
description = Apply coding style standards to code
deps =
    black
    isort
commands =
    isort {[vars]src_path} {[vars]tst_path}
    black {[vars]src_path} {[vars]tst_path}

[testenv:lint]
description = Check code against coding style standards
deps =
    -e {toxinidir}
    black
    flake8
    flake8-docstrings
    flake8-copyright
    flake8-builtins
    pyproject-flake8
    pep8-naming
    isort
    codespell
sitepackages = False
commands =
    codespell {toxinidir} --skip {toxinidir}/.git --skip {toxinidir}/.tox \
      --skip {toxinidir}/venv --skip {toxinidir}/.venv --skip {toxinidir}/cover --skip {toxinidir}/scripts
    # pflake8 wrapper supports config from pyproject.toml
    pflake8 {[vars]src_path} {[vars]tst_path}
    isort --check-only --diff {[vars]src_path} {[vars]tst_path}
    black --check --diff {[vars]src_path} {[vars]tst_path}

[testenv:unit]
description = Run unit tests
commands =
    coverage erase
    coverage run --source={[vars]src_path} \
        -m pytest {[vars]tst_path}unit -v --tb native -s {posargs}
    coverage html -d cover
    coverage xml -o cover/coverage.xml
    coverage report

[testenv:integration]
description = Run integration tests
commands =
    coverage erase
    coverage run --source={[vars]src_path} \
        -m pytest {[vars]tst_path}integration -v --tb native -s {posargs}
    coverage html -d cover
    coverage xml -o cover/coverage.xml
    coverage report

[testenv:cover]
description = Run both unit and integration tests
commands =
    coverage erase
    coverage run --source={[vars]src_path} \
        -m pytest {[vars]tst_path}unit -v --tb native -s {posargs}
    coverage run --append --source={[vars]src_path} \
        -m pytest {[vars]tst_path}integration -v --tb native -s {posargs}
    coverage html -d cover
    coverage xml -o cover/coverage.xml
    coverage report

[testenv:mypy]
description = Run mypy type checks
allowlist_externals = mypy
extras = dev
commands =
    mypy epa_orchestrator

[testenv:functional]
description = Run functional tests (requires running snap/daemon)
setenv =
    SOCKET_PATH = /var/snap/epa-orchestrator/current/data/epa.sock
deps =
    pytest
    pytest-mock
    pytest-cov
commands =
    python -m pytest tests/functional/ -v --tb=short --import-mode=importlib --confcutdir=tests/functional
