name: epa-orchestrator
base: core24
version: "2025.1"
summary: EPA orchestrator for OpenStack Hypervisor

description: |
  Provides Enhanced Platform Awareness (EPA) information, such as CPU pinning,
  via a Unix socket for consumption by other snaps.

grade: stable
confinement: strict

apps:
  daemon:
    command: "bin/daemon"
    daemon: simple
    plugs:
      - network-bind
      - sys-devices-system-node
    slots:
      - epa-info

  daily-backup:
    command: usr/sbin/logrotate -s $SNAP_DATA/logrotate.status $SNAP/etc/logrotate.d/state-json
    daemon: oneshot
    timer: 00:00

parts:
  bin:
    source: bin/
    plugin: dump
    organize:
      "*": bin/

  epa-orchestrator:
    plugin: python
    source: .
    python-packages:
      - pydantic
      - .

  logrotate:
    plugin: nil
    stage-packages:
      - logrotate

  logrotate-conf:
    plugin: dump
    source: snap/local/logrotate.conf
    source-type: file
    organize:
      logrotate.conf: etc/logrotate.d/state-json
    override-prime: |
      craftctl default
      chmod 0644 "$SNAPCRAFT_PRIME/etc/logrotate.d/state-json"

slots:
  epa-info:
    interface: content
    content: epa-info
    source:
      write:
        - $SNAP_DATA/data

plugs:
  sys-devices-system-node:
    interface: system-files
    read:
      - /sys/devices/system/node
