name: epa-orchestrator
base: core24
version: "2025.1"
summary: EPA orchestrator for OpenStack Hypervisor

description: |
  Provides Enhanced Platform Awareness (EPA) information, such as CPU pinning,
  via a Unix socket for consumption by other snaps.

grade: devel
confinement: strict

apps:
  daemon:
    command: "bin/daemon"
    daemon: simple
    plugs:
      - network-bind
      - sys-devices-system-node
    slots:
      - epa-info

parts:
  bin:
    source: bin/
    plugin: dump
    organize:
      "*": bin/

  epa-orchestrator:
    plugin: python
    source: .
    python-packages:
      - pydantic
      - .

slots:
  epa-info:
    interface: content
    content: epa-info
    source:
      write:
        - $SNAP_DATA/data

plugs:
  sys-devices-system-node:
    interface: system-files
    read:
      - /sys/devices/system/node
